failure test

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -7,9 +7,11 @@ jobs:
     steps:
       - name: Step 1
         run: sleep 20
+      - name: Fail
+        run: exit 1
       - name: Runs on Failure
         if: failure()
-        run: echo 'Runs only if failure'        
+        run: echo 'Runs only on failure'        
       - name: Runs on Success
         # This is not needed (DEFAULT BEAHAVIOR)
         if: success()
